### ISSUE TITLE
Java.Lang.OutOfMemoryError

### ISSUE THREAD

**Issue by AramMar** [mdc-maui/mdc-maui#7]
Hello
 thanks for all your work

I am trying to use mdc.

1. Created new maui project 
2. Install package from Nuget
3. Added necessary things
    https://mdc-maui.github.io/getting-started
4. Added label to the main page

    <?xml version="1.0" encoding="utf-8" ?>
    <ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                              xmlns:mdc="clr-namespace:Material.Components.Maui;assembly=Material.Components.Maui"
                 x:Class="MauiApp9.MainPage">
            <VerticalStackLayout
                Spacing="25"
                Padding="30,0"
                VerticalOptions="Center">
    
          <mdc:Label Text="Login" />
    
        </VerticalStackLayout>
    </ContentPage>

I am getting exception OutOfMemory, but without label on mainpage, app is running properly

thanks in advance

**Comment by yiszza** [comment]
Can you  provide a link to public reproduction project repository?

**Comment by AramMar** [comment]
Thank you for responding so quickly.

https://github.com/AramMar/MauiApp9.git

sometimes other exception also occers

https://github.com/AramMar/MauiApp9.git

**Comment by yiszza** [comment]
You missed step four: Add Material colors & styles in App.xaml
```xml
...
<mds:MaterialStyles />
...
```

**Comment by AramMar** [comment]
![App xaml](https://user-images.githubusercontent.com/106819289/218430072-446b685b-a039-450f-8091-aa7821e9cf6a.png)

sorry but there is in App.xaml, do you mean this one?
 xmlns:mds="clr-namespace:Material.Components.Maui.Styles;assembly=Material.Components.Maui"

**Comment by yiszza** [comment]
![image](https://user-images.githubusercontent.com/42995476/218430761-ecafd3ad-4cfd-4e1a-b1b0-c413fc6acefd.png)

**Comment by AramMar** [comment]
got it, thanks, sorry for your time

**Comment by yiszza** [comment]
😄
